@extends('layouts.app')
@section('title', 'Book Vehicle')
@section('content')
<a href="{{ route('salesman.test-drives.show', $testDrive) }}" class="text-secondary text-decoration-none">← Completed Test Drive</a>
<x-page-heading title="Book Vehicle" subtitle="Record the Customer's initial advance against this Vehicle model." eyebrow="TEST DRIVE → BOOKING PAYMENT" />
<form class="panel panel-body mt-3" method="POST" action="{{ route('salesman.customers.test-drives.book.store', [$customer, $testDrive]) }}">@csrf
<div class="row g-3"><div class="col-md-6"><div class="owner-strip h-100"><span class="eyebrow">CUSTOMER · LOCKED</span><strong class="d-block mt-1">{{ $customer->name }}</strong><small class="text-secondary">{{ $customer->phone }}</small></div></div><div class="col-md-6"><div class="owner-strip h-100"><span class="eyebrow">VEHICLE MODEL · LOCKED</span><strong class="d-block mt-1">{{ $testDrive->vehicle->model_year }} Mitsubishi {{ $testDrive->vehicle->name }}</strong><small class="text-secondary">{{ $testDrive->vehicle->variant }} · {{ $testDrive->vehicle->color }}</small></div></div>
<div class="col-md-6"><div class="info-list"><div class="info-item"><label>Salesman</label><strong>{{ $testDrive->salesman->name }}</strong></div><div class="info-item"><label>Dealer</label><strong>{{ $testDrive->salesman->dealer->name }}</strong></div><div class="info-item"><label>Completed Test Drive</label><strong>{{ $testDrive->scheduled_date->format('d M Y') }}</strong></div><div class="info-item"><label>Vehicle price</label><strong>৳{{ number_format($testDrive->vehicle->price, 0) }}</strong></div></div></div>
<div class="col-md-6"><div class="row g-3"><div class="col-12"><label class="form-label" for="booking_date">Booking date</label><input id="booking_date" name="booking_date" type="date" min="{{ today()->format('Y-m-d') }}" value="{{ old('booking_date', today()->format('Y-m-d')) }}" class="form-control @error('booking_date') is-invalid @enderror" required>@error('booking_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="expected_delivery_date">Expected delivery date <span class="text-secondary">(optional)</span></label><input id="expected_delivery_date" name="expected_delivery_date" type="date" value="{{ old('expected_delivery_date') }}" class="form-control @error('expected_delivery_date') is-invalid @enderror">@error('expected_delivery_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
<div class="col-md-5"><label class="form-label" for="booking_amount">Initial Booking / Advance Amount</label><div class="input-group"><span class="input-group-text">৳</span><input id="booking_amount" name="booking_amount" type="number" min="0.01" max="{{ $testDrive->vehicle->price }}" step="0.01" value="{{ old('booking_amount') }}" class="form-control @error('booking_amount') is-invalid @enderror" data-booking-amount required></div>@error('booking_amount')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
<div class="col-md-7"><div class="payment-summary" data-vehicle-price="{{ $testDrive->vehicle->price }}"><div><span>Vehicle Price</span><strong>৳{{ number_format($testDrive->vehicle->price, 0) }}</strong></div><div><span>Total Paid</span><strong data-total-paid>৳0</strong></div><div class="due"><span>Due Amount</span><strong data-due-amount>৳{{ number_format($testDrive->vehicle->price, 0) }}</strong></div></div></div>
<div class="col-12"><label class="form-label" for="notes">Booking notes <span class="text-secondary">(optional)</span></label><textarea id="notes" name="notes" maxlength="2000" rows="4" class="form-control @error('notes') is-invalid @enderror">{{ old('notes') }}</textarea>@error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="alert alert-warning mt-4 mb-0"><strong>Model booking only.</strong> Physical stock and chassis allocation remain a future workflow.</div><div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">Confirm Model Booking</button><a class="btn btn-outline-dark" href="{{ route('salesman.test-drives.show', $testDrive) }}">Cancel</a></div></form>
<script>document.addEventListener('DOMContentLoaded',()=>{const input=document.querySelector('[data-booking-amount]'),summary=document.querySelector('.payment-summary'),paid=document.querySelector('[data-total-paid]'),due=document.querySelector('[data-due-amount]');if(!input||!summary)return;const price=Number(summary.dataset.vehiclePrice),money=value=>'৳'+Math.max(0,value).toLocaleString('en-BD',{maximumFractionDigits:2});const update=()=>{const amount=Math.min(price,Math.max(0,Number(input.value)||0));paid.textContent=money(amount);due.textContent=money(price-amount);};input.addEventListener('input',update);update();});</script>
@endsection
