import './bootstrap';

document.addEventListener('DOMContentLoaded',()=>{
 const root=document.documentElement,themeToggle=document.querySelector('#themeToggle');
 const syncThemeToggle=()=>{const dark=root.dataset.theme!=='light',next=dark?'light':'dark';themeToggle?.setAttribute('aria-pressed',String(dark));themeToggle?.setAttribute('aria-label',`Switch to ${next} theme`);themeToggle?.setAttribute('title',`Switch to ${next} theme`)};
 syncThemeToggle();
 themeToggle?.addEventListener('click',()=>{const theme=root.dataset.theme==='dark'?'light':'dark';root.classList.add('theme-transitioning');root.dataset.theme=theme;root.style.colorScheme=theme;localStorage.setItem('mitsubishi-crm-theme',theme);syncThemeToggle();window.dispatchEvent(new CustomEvent('themechange',{detail:{theme}}));setTimeout(()=>root.classList.remove('theme-transitioning'),300)});
 const roleMetrics=(items)=>{const wrap=document.querySelector('.command-metrics');if(!wrap)return;wrap.innerHTML=items.map(([label,value,note])=>`<div class="command-metric"><small>${label}</small><strong>${value}</strong><span>${note}</span></div>`).join('')};
 if(location.pathname==='/admin/dashboard'){roleMetrics([['Total Dealers','4','Entire network'],['Total Salesmen','12','Across all outlets'],['Total Customers','350','Active relationships'],['Total Test Drives','74','Network activity'],['Total Bookings','48','Current month'],['Cars Sold','48','↑ 12.5%'],['Revenue','৳8.4M','Current month']]);document.querySelector('.command-metrics')?.style.setProperty('grid-template-columns','repeat(7,minmax(0,1fr))')}
 if(location.pathname==='/dealer/dashboard'){roleMetrics([['Salesmen','4','Uttara team'],['Active Customers','126','Uttara only'],['Test Drives','18','This month'],['Bookings','12','Uttara only'],['Revenue','৳2.4M','Uttara dealership']])}
 const sidebar=document.querySelector('.sidebar');
 document.querySelector('[data-sidebar-toggle]')?.addEventListener('click',()=>sidebar?.classList.toggle('open'));
 const searchBox=document.querySelector('[data-search-box]'),globalSearch=document.querySelector('#globalSearch');globalSearch?.addEventListener('focus',()=>searchBox?.classList.add('is-open'));globalSearch?.addEventListener('input',()=>searchBox?.classList.add('is-open'));document.addEventListener('click',e=>{if(searchBox&&!searchBox.contains(e.target))searchBox.classList.remove('is-open')});
 document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('input',()=>{const q=el.value.toLowerCase();document.querySelectorAll('[data-search-row]').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))}));
 document.querySelectorAll('[data-demo-action]').forEach(btn=>btn.addEventListener('click',()=>{const toast=document.querySelector('.toast-demo');if(toast){toast.textContent=btn.dataset.message||'Action completed successfully';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}}));
 document.querySelectorAll('.slot:not(.busy)').forEach(slot=>slot.addEventListener('click',()=>{slot.classList.add('is-selected');setTimeout(()=>slot.classList.remove('is-selected'),260);const input=document.querySelector('#bookingTime');if(input)input.value=slot.dataset.time||'';bootstrap.Modal.getOrCreateInstance(document.querySelector('#bookingModal')).show()}));
 document.querySelectorAll('[data-chat-contact]').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('[data-chat-contact]').forEach(x=>x.classList.remove('active'));c.classList.add('active');document.querySelector('#chatName').textContent=c.dataset.name}));
 document.querySelector('#sendMessage')?.addEventListener('click',()=>{const input=document.querySelector('#messageInput');if(!input.value.trim())return;const m=document.createElement('div');m.className='message out';m.innerHTML=`${input.value.replace(/[<>]/g,'')}<small>Just now</small>`;document.querySelector('.messages').appendChild(m);input.value='';m.scrollIntoView({behavior:'smooth'})});
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 document.querySelectorAll('.chart').forEach(chart=>{
  const original=[...chart.querySelectorAll('.bar')].map(bar=>Math.round(parseFloat(bar.style.height)||0));if(!original.length)return;
  const months=['Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug'],dealer=chart.closest('.panel')?.textContent.includes('My Sales Performance');
  const units=original.map(v=>dealer?Math.max(2,Math.round(v/18)):Math.max(25,Math.round(v/2.1))),max=dealer?10:90,revenue=units.map((v,i)=>dealer?+(v*.16+(i%3)*.03).toFixed(2):+(v*.047+(i%3)*.08).toFixed(1));
  const W=760,H=270,L=48,R=18,T=22,B=42,plotW=W-L-R,plotH=H-T-B,x=i=>L+i*(plotW/11),y=v=>T+plotH-(v/max)*plotH;
  const points=units.map((v,i)=>`${x(i)},${y(v)}`).join(' '),area=`${L},${T+plotH} ${points} ${x(11)},${T+plotH}`;
  const revenueMax=Math.max(...revenue)*1.14,revPoints=revenue.map((v,i)=>`${x(i)},${T+plotH-(v/revenueMax)*plotH}`).join(' ');
  const total=units.reduce((a,b)=>a+b,0),growth=Math.round((units[11]-units[0])/units[0]*100),avg=(revenue.reduce((a,b)=>a+b,0)/12).toFixed(dealer?2:1);
  const grid=[0,.25,.5,.75,1].map(p=>`<line x1="${L}" y1="${T+plotH*p}" x2="${W-R}" y2="${T+plotH*p}"/><text x="${L-10}" y="${T+plotH*p+4}" text-anchor="end">${Math.round(max*(1-p))}</text>`).join('');
  const labels=months.map((m,i)=>`<text class="trend-month" x="${x(i)}" y="${H-13}" text-anchor="middle">${m}</text>`).join('');
  const dots=units.map((v,i)=>`<circle class="trend-point" cx="${x(i)}" cy="${y(v)}" r="5" data-month="${months[i]}" data-units="${v}" data-revenue="${revenue[i]}"/>`).join('');
  chart.previousElementSibling?.classList.add('legacy-chart-legend');
  chart.innerHTML=`<div class="analytics-summary"><div><span>YTD UNITS</span><strong>${total}</strong><em>↑ ${growth}% year over year</em></div><div><span>AVG. MONTHLY REVENUE</span><strong>৳${avg}M</strong><em>Across ${dealer?'Uttara':'dealer network'}</em></div><div><span>PEAK MONTH</span><strong>August</strong><em>${units[11]} vehicles · ৳${revenue[11]}M</em></div></div><div class="trend-legend"><span><i></i>Units sold</span><span><i></i>Revenue trend</span><small>Hover points for details</small></div><div class="trend-scroll"><svg class="trend-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Twelve month sales and revenue trend"><g class="trend-grid">${grid}</g><polygon class="trend-area" points="${area}"/><polyline class="trend-revenue" points="${revPoints}"/><polyline class="trend-line" points="${points}"/>${dots}${labels}</svg></div>`;
 });
 document.querySelectorAll('[data-count]').forEach((el,i)=>{if(reduced)return;const raw=el.dataset.count,goal=parseFloat(raw),prefix=el.dataset.prefix||'',suffix=el.dataset.suffix||'',decimals=(raw.split('.')[1]||'').length,start=performance.now();el.textContent=prefix+'0'+suffix;const tick=now=>{const p=Math.min((now-start)/520,1),ease=1-Math.pow(1-p,3);el.textContent=prefix+(goal*ease).toFixed(decimals)+suffix;if(p<1)requestAnimationFrame(tick)};setTimeout(()=>requestAnimationFrame(tick),i*45)});
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal,.activity').forEach((el,i)=>{el.style.setProperty('--delay',`${(i%6)*55}ms`);observer.observe(el)});
 const tip=document.querySelector('.chart-tip');document.querySelectorAll('.bar-wrap').forEach((bar,i)=>{bar.addEventListener('mouseenter',e=>{if(!tip)return;tip.innerHTML=`<strong>${bar.textContent.trim()}</strong><br>Cars Sold: ${Math.round(parseFloat(bar.querySelector('.bar')?.style.height||0)/14)}<br>Revenue: ৳${(1.2+i*.08).toFixed(1)}M`;tip.classList.add('show')});bar.addEventListener('mousemove',e=>{tip.style.left=`${e.clientX+14}px`;tip.style.top=`${e.clientY-58}px`});bar.addEventListener('mouseleave',()=>tip?.classList.remove('show'))});
 document.querySelectorAll('.trend-point').forEach(point=>{point.addEventListener('mouseenter',()=>{if(!tip)return;tip.innerHTML=`<strong>${point.dataset.month} performance</strong><br>${point.dataset.units} vehicles sold<br>৳${point.dataset.revenue}M revenue`;tip.classList.add('show')});point.addEventListener('mousemove',e=>{tip.style.left=`${e.clientX+14}px`;tip.style.top=`${e.clientY-64}px`});point.addEventListener('mouseleave',()=>tip?.classList.remove('show'))});
 document.querySelectorAll('[data-message="Test drive booking confirmed"]').forEach(btn=>{btn.removeAttribute('data-bs-dismiss');btn.setAttribute('data-confirm-booking','')});
 document.querySelectorAll('[data-confirm-booking]').forEach(btn=>btn.addEventListener('click',()=>{const modal=btn.closest('.modal-content');modal.innerHTML='<div class="booking-success"><div class="success-check">✓</div><h3>Booking confirmed</h3><p class="fs-5 fw-bold">BK-00124</p><p class="text-secondary">Vehicle reserved for Rahim Ahmed.</p><button class="btn btn-primary" data-bs-dismiss="modal">Done</button></div>'}));
 document.querySelectorAll('.slot.busy').forEach(slot=>slot.addEventListener('click',()=>{const toast=document.querySelector('.toast-demo');if(toast){toast.textContent='Booked slot · Test drive details are unavailable for editing';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}}));
 const bookingModal=document.querySelector('#bookingModal');bookingModal?.addEventListener('show.bs.modal',()=>{const body=bookingModal.querySelector('.modal-body');if(body&&!body.querySelector('.booking-vehicle-preview')){const img=document.createElement('img');img.className='booking-vehicle-preview';img.src='/assets/images/vehicles/outlander-2026.png';img.alt='Mitsubishi Outlander';body.prepend(img)}});
});
