@extends('layouts.app')
@section('title', $customer->name)
@section('content')
<div data-crm-record data-record-id="{{ $customer->id }}">
<div class="d-flex justify-content-between align-items-center gap-3"><a href="{{ route('salesman.customers.index') }}" class="text-secondary text-decoration-none">← My Customers</a><div class="d-flex gap-2"><a class="btn btn-primary" href="{{ route('salesman.customers.edit', $customer) }}">Edit Customer</a><form method="POST" action="{{ route('salesman.customers.destroy', $customer) }}" data-crm-ajax data-remove-record="true" data-success-url="{{ route('salesman.customers.index') }}" data-success-label="Back to My Customers" data-confirm-title="Delete Customer?" data-confirm-message="This Customer will be permanently removed from your records." data-confirm-button="Delete Customer" data-confirm-style="danger">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Delete Customer</button></form></div></div>
@if(session('success'))<div class="alert alert-success mt-3">{{ session('success') }}</div>@endif
<div class="d-flex justify-content-end mt-3"><a class="btn btn-primary" href="{{ route('salesman.customers.test-drives.create', $customer) }}"><i class="bi bi-calendar2-plus"></i> Schedule Test Drive</a></div>
<div class="profile-hero my-3"><span class="avatar red">{{ strtoupper(substr($customer->name, 0, 2)) }}</span><div style="z-index:1"><div class="eyebrow">{{ strtoupper($customer->status) }} CUSTOMER</div><h2>{{ $customer->name }}</h2><div class="text-white-50">{{ $customer->phone }} · {{ $customer->email ?: 'No email' }}</div></div></div>
<div class="row g-3">
    <div class="col-lg-8"><div class="panel h-100"><div class="panel-header"><div><div class="eyebrow">CUSTOMER PROFILE</div><h3 class="panel-title mt-1">Contact information</h3></div><x-status :status="ucfirst($customer->status)" /></div><div class="panel-body"><div class="info-list">
        <div class="info-item"><label>Name</label><strong>{{ $customer->name }}</strong></div><div class="info-item"><label>Phone</label><strong>{{ $customer->phone }}</strong></div><div class="info-item"><label>Email</label><strong>{{ $customer->email ?: '—' }}</strong></div><div class="info-item"><label>City</label><strong>{{ $customer->city ?: '—' }}</strong></div><div class="info-item"><label>Address</label><strong>{{ $customer->address ?: '—' }}</strong></div><div class="info-item"><label>Status</label><strong>{{ ucfirst($customer->status) }}</strong></div>
    </div></div></div></div>
    <div class="col-lg-4"><div class="panel"><div class="panel-header"><h3 class="panel-title">Ownership context</h3></div><div class="panel-body info-list"><div class="info-item"><label>Salesman</label><strong>{{ $customer->salesman->name }}</strong></div><div class="info-item"><label>Dealer</label><strong>{{ $customer->salesman->dealer?->name ?? 'No Dealer assigned' }}</strong></div><div class="info-item"><label>Access</label><strong>Read only</strong></div></div></div></div>
</div>
<div class="panel mt-3"><div class="panel-header"><div><div class="eyebrow">TEST DRIVE → BOOKING</div><h3 class="panel-title mt-1">Customer appointments</h3></div><a class="btn btn-sm btn-primary" href="{{ route('salesman.customers.test-drives.create', $customer) }}">Schedule Test Drive</a></div>@if($customer->testDrives->isEmpty())<div class="panel-body"><p class="text-secondary mb-0">No Test Drives scheduled for this Customer.</p></div>@else<div class="table-responsive"><table class="table crm-table align-middle"><thead><tr><th>Vehicle</th><th>Date</th><th>Status</th><th>Next step</th></tr></thead><tbody>@foreach($customer->testDrives as $testDrive)<tr><td><strong>{{ $testDrive->vehicle->name }}</strong><small class="d-block text-secondary">{{ $testDrive->vehicle->variant }}</small></td><td>{{ $testDrive->scheduled_date->format('d M Y') }}</td><td><x-status :status="$testDrive->status->label()" /></td><td>@if($testDrive->booking)<a class="btn btn-sm btn-primary" href="{{ route('salesman.bookings.show', $testDrive->booking) }}">Open Booking</a>@elseif($testDrive->status === \App\Enums\TestDriveStatus::Completed)<a class="btn btn-sm btn-primary" href="{{ route('salesman.customers.test-drives.book.create', [$customer, $testDrive]) }}">Book Vehicle</a>@else<a class="btn btn-sm btn-outline-dark" href="{{ route('salesman.test-drives.show', $testDrive) }}">Open Test Drive</a>@endif</td></tr>@endforeach</tbody></table></div>@endif</div>
</div>
@endsection
