@csrf
@if(isset($customer)) @method('PUT') @endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Customer name</label><input id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $customer->name ?? '') }}" required maxlength="255">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="phone">Phone</label><input id="phone" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone', $customer->phone ?? '') }}" required maxlength="30">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">Email</label><input id="email" name="email" type="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email', $customer->email ?? '') }}" maxlength="255">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="city">City</label><input id="city" name="city" class="form-control @error('city') is-invalid @enderror" value="{{ old('city', $customer->city ?? '') }}" maxlength="255">@error('city')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-8"><label class="form-label" for="salesman_id">Salesman owner</label><select id="salesman_id" name="salesman_id" class="form-select @error('salesman_id') is-invalid @enderror" required><option value="">Select a Salesman</option>@foreach($salesmen as $salesman)<option value="{{ $salesman->id }}" @selected(old('salesman_id', $customer->salesman_id ?? '') == $salesman->id)>{{ $salesman->name }} — {{ $salesman->dealer?->name ?? 'No Dealer assigned' }}</option>@endforeach</select>@error('salesman_id')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">The Customer's Dealer is derived from this Salesman's current Dealer assignment.</div></div>
    <div class="col-md-4"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $customer->status ?? 'new') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="address">Address</label><textarea id="address" name="address" class="form-control @error('address') is-invalid @enderror" rows="4">{{ old('address', $customer->address ?? '') }}</textarea>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">{{ isset($customer) ? 'Save Changes' : 'Create Customer' }}</button><a class="btn btn-outline-dark" href="{{ isset($customer) ? route('customers.show', $customer) : route('customers.index') }}">Cancel</a></div>
