@extends('layouts.app')
@section('title', 'My Test Drives')
@section('content')
<x-page-heading title="My Test Drives" subtitle="Manage upcoming appointments for Customers personally assigned to you." eyebrow="SALESMAN · APPOINTMENT WORKFLOW"><a class="btn btn-primary" href="{{ route('salesman.customers.index') }}"><i class="bi bi-plus-lg"></i> Schedule from Customer</a></x-page-heading>
@if(session('success'))<div class="alert alert-success mt-3">{{ session('success') }}</div>@endif
<div class="row g-3 my-1"><div class="col-md-4"><div class="stat-card"><span class="eyebrow">TOTAL APPOINTMENTS</span><strong>{{ $testDrives->total() }}</strong><small>Your scoped Test Drive workflow</small></div></div><div class="col-md-4"><div class="stat-card"><span class="eyebrow">UPCOMING</span><strong>{{ $testDrives->getCollection()->where('scheduled_date', '>=', today())->count() }}</strong><small>Visible on this page</small></div></div><div class="col-md-4"><div class="stat-card"><span class="eyebrow">REMINDER READY</span><strong><i class="bi bi-bell"></i></strong><small>Date, time and Customer contact available</small></div></div></div>
<div class="panel mt-3"><div class="panel-header"><div><div class="eyebrow">APPOINTMENT PIPELINE</div><h3 class="panel-title mt-1">Upcoming and recent Test Drives</h3></div></div>
@if($testDrives->isEmpty())<div class="panel-body text-center py-5"><div class="crm-empty-icon"><i class="bi bi-calendar2-plus"></i></div><h3>No Test Drives scheduled yet</h3><p class="text-secondary">Open one of your Customers to schedule their first Test Drive.</p><a class="btn btn-primary" href="{{ route('salesman.customers.index') }}">Open My Customers</a></div>
@else<div class="table-responsive"><table class="table crm-table align-middle"><thead><tr><th>Customer</th><th>Vehicle</th><th>Appointment</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($testDrives as $testDrive)<tr><td><strong>{{ $testDrive->customer->name }}</strong><small class="d-block text-secondary">{{ $testDrive->customer->phone }}</small></td><td><strong>{{ $testDrive->vehicle->model_year }} {{ $testDrive->vehicle->name }}</strong><small class="d-block text-secondary">{{ $testDrive->vehicle->variant }} · {{ $testDrive->vehicle->color }}</small></td><td><strong>{{ $testDrive->scheduled_date->format('d M Y') }}</strong><small class="d-block text-secondary">{{ \Illuminate\Support\Carbon::parse($testDrive->scheduled_time)->format('g:i A') }}</small></td><td><x-status :status="$testDrive->status->label()" /></td><td><a class="btn btn-sm btn-primary" href="{{ route('salesman.test-drives.show', $testDrive) }}">Open</a><a class="btn btn-sm btn-outline-dark" href="{{ route('salesman.test-drives.edit', $testDrive) }}">Manage</a></td></tr>@endforeach</tbody></table></div>@if($testDrives->hasPages())<div class="panel-body border-top">{{ $testDrives->links() }}</div>@endif
@endif</div>
@endsection
