@extends('layouts.app')
@section('title', 'Test Drive · '.$testDrive->customer->name)
@section('content')
<div id="test-drive-workspace">
<div class="d-flex justify-content-between align-items-center gap-3 flex-wrap"><a href="{{ route('salesman.test-drives.index') }}" class="text-secondary text-decoration-none">← My Test Drives</a><a class="btn btn-outline-dark" href="{{ route('salesman.test-drives.edit', $testDrive) }}">Full edit</a></div>
@if(session('success'))<div class="alert alert-success mt-3">{{ session('success') }}</div>@endif
@if($testDrive->booking)<div class="alert alert-success mt-3 d-flex justify-content-between align-items-center gap-3"><span><strong>Customer said yes.</strong> A model Booking exists for this Test Drive.</span><a class="btn btn-sm btn-primary" href="{{ route('salesman.bookings.show', $testDrive->booking) }}">Open Booking</a></div>
@elseif($testDrive->status === \App\Enums\TestDriveStatus::Completed)<div class="panel panel-body mt-3 d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><div class="eyebrow">CUSTOMER DECISION · YES</div><strong class="d-block mt-1">Continue this completed Test Drive into a Vehicle model Booking.</strong></div><a class="btn btn-primary" href="{{ route('salesman.customers.test-drives.book.create', [$testDrive->customer, $testDrive]) }}"><i class="bi bi-journal-check"></i> Book Vehicle</a></div>
@endif
<div class="appointment-hero my-3"><div><div class="eyebrow">TEST DRIVE APPOINTMENT · #{{ $testDrive->id }}</div><h2>{{ $testDrive->scheduled_date->format('l, d F Y') }}</h2><p>{{ \Illuminate\Support\Carbon::parse($testDrive->scheduled_time)->format('g:i A') }} · {{ $testDrive->vehicle->model_year }} Mitsubishi {{ $testDrive->vehicle->name }}</p></div><x-status :status="$testDrive->status->label()" /></div>
<div class="row g-3"><div class="col-xl-8"><div class="row g-3">
<div class="col-md-6"><div class="panel h-100"><div class="panel-header"><div><div class="eyebrow">CUSTOMER</div><h3 class="panel-title mt-1">{{ $testDrive->customer->name }}</h3></div></div><div class="panel-body info-list"><div class="info-item"><label>Phone</label><strong>{{ $testDrive->customer->phone }}</strong></div><div class="info-item"><label>Email</label><strong>{{ $testDrive->customer->email ?: '—' }}</strong></div><a class="btn btn-sm btn-outline-dark mt-3" href="{{ route('salesman.customers.show', $testDrive->customer) }}">Open Customer</a></div></div></div>
<div class="col-md-6"><div class="panel h-100"><div class="panel-header"><div><div class="eyebrow">VEHICLE</div><h3 class="panel-title mt-1">{{ $testDrive->vehicle->model_year }} {{ $testDrive->vehicle->name }}</h3></div></div><div class="panel-body info-list"><div class="info-item"><label>Variant</label><strong>{{ $testDrive->vehicle->variant }}</strong></div><div class="info-item"><label>Color</label><strong>{{ $testDrive->vehicle->color }}</strong></div><div class="info-item"><label>Inventory status</label><strong>{{ str($testDrive->vehicle->status)->replace('_', ' ')->title() }}</strong></div></div></div></div>
<div class="col-12"><div class="panel"><div class="panel-header"><div><div class="eyebrow">APPOINTMENT NOTES</div><h3 class="panel-title mt-1">Sales context</h3></div></div><div class="panel-body"><p class="mb-0 {{ $testDrive->notes ? '' : 'text-secondary' }}">{{ $testDrive->notes ?: 'No notes have been added for this Test Drive.' }}</p></div></div></div>
</div></div>
<div class="col-xl-4"><div class="panel appointment-control"><div class="panel-header"><div><div class="eyebrow">QUICK WORKFLOW</div><h3 class="panel-title mt-1">Update appointment</h3></div></div><div class="panel-body"><form method="POST" action="{{ route('salesman.test-drives.update', $testDrive) }}" data-crm-ajax data-refresh-selector="#test-drive-workspace">@csrf @method('PUT')
<label class="form-label" for="quick_status">Status</label><select id="quick_status" name="status" class="form-select" required>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($testDrive->status === $status)>{{ $status->label() }}</option>@endforeach</select>
<input type="hidden" name="slot_id" value="{{ $testDrive->slot_id }}"><div class="owner-strip mt-3"><span class="eyebrow">SELECTED SLOT</span><strong class="d-block mt-1">{{ $testDrive->slot ? \Illuminate\Support\Carbon::parse($testDrive->slot->start_time)->format('g:i A').' – '.\Illuminate\Support\Carbon::parse($testDrive->slot->end_time)->format('g:i A') : 'Legacy appointment time' }}</strong><small class="text-secondary">Use Full edit to reschedule into another available Slot.</small></div>
<label class="form-label mt-3" for="quick_notes">Notes</label><textarea id="quick_notes" class="form-control" name="notes" maxlength="2000" rows="3">{{ $testDrive->notes }}</textarea><button class="btn btn-primary w-100 mt-3" type="submit">Save appointment update</button></form><hr><div class="info-list"><div class="info-item"><label>Salesman</label><strong>{{ $testDrive->salesman->name }}</strong></div><div class="info-item"><label>Dealer</label><strong>{{ $testDrive->salesman->dealer->name }}</strong></div></div></div></div></div>
</div></div>
@endsection
